from .base import *
from .chapter import *
from .common import *
from .course import *
from .department import *
from .institution import *
from .permission import *
from .student import *
from .tag import *
from .stats import *
from .wechat import *